export const DISPOSABLE_EMAIL_DOMAINS: ReadonlySet<string> = new Set([
  // mailinator family
  "mailinator.com",
  "mailinator.net",
  "mailinator.org",
  "mailinator2.com",
  "sogetthis.com",
  "mailin8r.com",
  "mailinater.com",

  // yopmail family
  "yopmail.com",
  "yopmail.net",
  "yopmail.fr",
  "cool.fr.nf",
  "jetable.fr.nf",

  // temp-mail / tempmail family
  "tempmail.com",
  "temp-mail.org",
  "temp-mail.io",
  "tempmailo.com",
  "tempmail.net",
  "tempmail.dev",
  "tmpmail.org",
  "tmpmail.net",
  "tmpeml.com",

  // trashmail family
  "trashmail.com",
  "trashmail.net",
  "trashmail.me",
  "trash-mail.com",
  "trashmail.io",
  "trashinbox.com",

  // guerrillamail family
  "guerrillamail.com",
  "guerrillamail.net",
  "guerrillamail.org",
  "guerrillamail.biz",
  "guerrillamail.de",
  "guerrillamailblock.com",
  "sharklasers.com",
  "grr.la",
  "pokemail.net",
  "spam4.me",

  // 10minutemail family
  "10minutemail.com",
  "10minutemail.net",
  "10minemail.com",
  "10minutemail.co.uk",
  "20minutemail.com",

  // fakeinbox / fake mail family
  "fakeinbox.com",
  "fakemail.net",
  "fakemailgenerator.com",
  "fakemailgenerator.net",

  // test / example reserved domains
  "test.com",
  "example.com",
  "example.net",
  "example.org",
  "test.org",
  "test.net",

  // discard / disposable utility domains
  "discard.email",
  "discardmail.com",
  "discardmail.de",
  "dispostable.com",
  "disposablemail.com",
  "disposableinbox.com",
  "throwawaymail.com",
  "throwaway.email",
  "getnada.com",
  "getairmail.com",
  "spamgourmet.com",
  "spambog.com",
  "spambox.us",
  "mytemp.email",
  "emailondeck.com",
  "mintemail.com",
  "mohmal.com",
  "moakt.com",
  "moakt.cc",
  "burnermail.io",
  "maildrop.cc",
  "mailnesia.com",
  "mailcatch.com",
  "mail-temp.com",
  "mail7.io",
  "emailtemporario.com.br",
  "tempinbox.com",
  "dropmail.me",
  "inboxbear.com",
  "incognitomail.com",
  "anonbox.net",
  "zippymail.info",
  "crazymailing.com",
  "fleckens.hu",
  "harakirimail.com",
  "mailnull.com",
  "spamfree24.org",
  "mt2015.com",
  "mt2014.com",
  "33mail.com",
  "deadaddress.com",
  "mailexpire.com",
]);